require: rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'Gemfile'
    - 'Gemfile.lock'
    - 'Rakefile'

Rails:
  Enabled: true

# 以下に追加の設定を書くことができます
